services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: elixir_ai
      POSTGRES_PASSWORD: elixir_ai
      POSTGRES_DB: elixir_ai_dev
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
