apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-ha-elixir
  namespace: ai-ha-elixir
spec:
  ingressClassName: nginx
  rules:
    - host: ai-ha.alexmickelson.guru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-ha-elixir
                port:
                  number: 80
