apiVersion: v1
kind: Namespace
metadata:
  name: ai-ha-elixir
---
apiVersion: v1
kind: Service
metadata:
  name: ai-ha-elixir-headless
  namespace: ai-ha-elixir
spec:
  clusterIP: None
  selector:
    app: ai-ha-elixir
  ports:
    - name: http
      port: 4000
    - name: epmd
      port: 4369
    - name: beam
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-ha-elixir
  namespace: ai-ha-elixir
spec:
  selector:
    app: ai-ha-elixir
  ports:
    - name: http
      port: 80
      targetPort: 4000
